apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: app-props-test

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Props test
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "App property app_prop1: ${{vars.app_prop1}}"
          echo "App property app_prop1: ${{vars.app_prop2}}"
          echo "Inherited DOCKER_USERNAME: ${{vars.DOCKER_USERNAME}}"
          echo "Inherited DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}"
          echo "App secret us_test_secret_app: ${{secrets.us_test_secret_app}}"
          echo "Org secret us_test_secret_org: ${{secrets.us_test_secret_org}}"
          
          if [ "${{secrets.us_test_secret_app}}" = "${{secrets.us_test_secret_org}}" ]; then
            echo "App secret matches org secret value"
          else 
            echo "App secret does not match org secret value"
          fi


          
          
