apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  app:
    uses: "./.cloudbees/workflows/manual-approval.yaml"