apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: app-deployer
on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true  
jobs:
  MyAppAPIs:
    if: ${{ fromJSON(inputs.manifest).MyAppAPIs.Art11.deploy }} || ${{ fromJSON(inputs.manifest).MyAppAPIs.Art12.deploy }}
    uses: urvashisingh/my-go-app/.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ toJSON(fromJSON(inputs.manifest).MyAppAPIs) }}
      environment: ${{ inputs.environment }}
  MyAppFE:
    if: ${{ fromJSON(inputs.manifest).MyAppFE.Art21.deploy }}
    uses: urvashisingh/app3/.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ toJSON(fromJSON(inputs.manifest).MyAppFE) }}
      environment: ${{ inputs.environment }}
