apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow
on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
  workflow_call:
    inputs:
      manifest:
        type: string
jobs:
  MyAppAPIs:
    if: ${{ fromJSON(inputs.manifest)."Comp 1"."Art1".deployed }}
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppAPIs
      artifactVersion: 2.0.5-0.0.17
      environment: pre-prod
  MyAppFE:
    if: ${{ fromJSON(inputs.manifest)."Comp 1"."Art2".deployed }}
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppFE
      artifactVersion: 3.0.3-0.0.14
      environment: pre-prod
  MyAppBE:
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppBE
      artifactVersion: 2.2.0-0.0.21
      environment: pre-prod