apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: app-deployer
description: Application workflow that deploys component artifacts for the application to a given environment using the given manifest
on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true  
jobs:
  MyAppAPIs:
    if: ${{ fromJSON(inputs.manifest).MyAppAPIs.Art11.deploy }} || ${{ fromJSON(inputs.manifest).MyAppAPIs.Art12.deploy }}
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppAPIs
      artifactVersion: ${{ fromJSON(inputs.manifest).MyAppAPIs.Art11.version }}
      environment: ${{ inputs.environment }}
  MyAppFE:
    if: ${{ fromJSON(inputs.manifest).MyAppFE.Art21.deploy }}
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppFE
      artifactVersion: 3.0.3-0.0.14
      environment: ${{ inputs.environment }}
  MyAppBE:
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppBE
      artifactVersion: 2.2.0-0.0.21
      environment: ${{ inputs.environment }}