apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: app-deployer
on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true  
jobs:
  temp-process-manifest:
    outputs:
      manifest: ${{ steps.step1.outputs.manifest }}
  app1:
    needs: temp-process-manifest
    if: ${{ fromJSON(needs.temp-process-manifest.outputs.manifest).app1.deploy }}
    uses: urvashisingh/app1/.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ toJSON(fromJSON(needs.temp-process-manifest.outputs.manifest).app1) }}
      environment: ${{ inputs.environment }}
  app3:
    needs: temp-process-manifest
    if: ${{ fromJSON(needs.temp-process-manifest.outputs.manifest).app3.deploy }}
    uses: urvashisingh/app3/.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ toJSON(fromJSON(needs.temp-process-manifest.outputs.manifest).app3) }}
      environment: ${{ inputs.environment }}
