apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: environmental approval
on:
  workflow_dispatch:
    inputs:
      TestTag:
        type: choice
        options:
          - "@Login"
          - "@MarketplaceTest"
          - "@SecurityCenterTest"
          - "@SlaConfig"
          - "@SummaryWidget"
          - "@AllScanners"
          - "@WorkflowTest"
          - "@ActionTest"
          - "@EnvironmentTest"
          - "@PropertyTest"
          - "@NotificationTest"
          - "@FM"
          - "@IntegrationTest"
          - "@OrganizationTest"
          - "@TestInsights"
          - "@JenkinsManagementTest"
          - "@UserManagementTest"
          - "@Bitbucket"
          - "@Cleanup"
          - '@UserInviteTest'
          - "@VSMDashboard"
          - "@CoreRegression"
        default: "@Login"
        required: true
        description: Choose test tags to run tests related to that feature
  workflow_call:
jobs:
  build:
    environment: requires-approval
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world2"
            build:
  work:
    needs: build
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
