apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
  workflow_call:  

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - approval-job
  approval-job:
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: 4bc37dfe-459a-11ed-a6a3-42010a83ae66,0cb88e48-03d3-11eb-9d67-42010a83ae35
      notifyAllEligibleUsers: false
      approvalInputs: |
        in1:
          type: string
          required: true
          description: One of the required approver inputs
        in2:
          type: number
          description: a numeric input
        in3:
          type: choice
          options:
            - op1
            - op2
          default: op2
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  echo-approval-inputs:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Echo approver inputs
        shell: sh
        run: |
          echo comments: ${{needs.approval-job.outputs.comments }}
          echo in1 input: ${{ fromJSON(needs.approval-job.outputs.approvalInputValues).in1 }}
          echo in2 input: ${{ fromJSON(needs.approval-job.outputs.approvalInputValues).in2 }}
          echo in3 input: ${{ fromJSON(needs.approval-job.outputs.approvalInputValues).in3 }}
    needs:
      - approval-job
