apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: my-assisted-release-wf
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - Prod
jobs:
  Prod:
    environment: Prod
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ cloudbees.job.environment }}
