apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: my-staged-workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: Relese manifest with the artifact version details passed by the application release in JSON format
metadata:
  stages/v1alpha1:
    - name: qa
      jobs:
        - deploy-to-qa
    - name: preprod
      jobs:
        - deploy-to-preprod
    - name: prod
      jobs:
        - deploy-to-prod
jobs:
  deploy-to-qa:
    steps:
      - name: Deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo Deploying...
  deploy-to-preprod:
    needs:
      - deploy-to-qa
    steps:
      - name: Deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo Deploying...
  deploy-to-prod:
    needs:
      - deploy-to-preprod
    steps:
      - name: Deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo Deploying...
