apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My application release workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
      test:
        type: string
        default: reusable-deploy-wf
jobs:
  env1-deploy-comp1:
    uses: urvashisingh/my-go-app/.cloudbees/workflows/${{inputs.test}}.yaml@main
    with:
      manifest: ${{ inputs.manifest }}
      env: env1
  env2-deploy-comp1:
    uses: urvashisingh/my-go-app/.cloudbees/workflows/reusable-deploy-wf.yaml@main
    with:
      manifest: ${{ inputs.manifest }}
      env: env2

