apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      str:
        type: string
      options:
        type: choice
        options:
          - op1
        default: op1
        
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://esolang/jq:latest
        shell: sh
        run: |
          URL=${{ cloudbees.api.url }}/v3/artifactinfos 
          echo "`date` - Calling: $URL"
          curl -X POST -kv -H "Authorization: Bearer ${{ cloudbees.api.token }}" "$URL" -d '{"runId":"${{ cloudbees.run_id }}", "name": "a1", "url": "url1", "version": "1.2", "runAttempt":"${{ cloudbees.run_attempt }}"}'
          echo "`date` - Done"
