apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest1dsddsdsdsd:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: preprod-us-west-2
      jobs:
        - deploy-to-preprod-us-west-2
    - name: preprod-us-east-1
      jobs:
        - deploy-to-preprod-us-east-1
jobs:
  deploy-to-preprod-us-west-2:
    steps:
      - name: Deploy to preprod-us-west-2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to preprod-us-west-2"
  deploy-to-preprod-us-east-1:
    needs:
      - deploy-to-preprod-us-west-2
    steps:
      - name: Deploy to preprod-us-east-1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to preprod-us-east-1"
