apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in
          application releases. Refer to
          https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest
          for the expected format
metadata:
  stages/v1alpha1:
    - name: qa
      jobs:
        - deploy-to-qa
    - name: pre-prod
      jobs:
        - deploy-to-pre-prod
    - name: prod
      jobs:
        - deploy-to-prod
jobs:
  deploy-to-qa:
    environment: qa
    steps:
      - run: echo "Deploying to qa"
        uses: docker://golang:1.20.3-alpine3.17
        name: Deploy to qa
        shell: sh
        kind: deploy
  deploy-to-pre-prod:
    needs:
      - deploy-to-qa
    environment: pre-prod
    steps:
      - run: echo "Deploying to pre-prod"
        uses: docker://golang:1.20.3-alpine3.17
        name: Deploy to pre-prod
        shell: sh
        kind: deploy
  deploy-to-prod:
    needs:
      - deploy-to-pre-prod
    environment: prod
    steps:
      - run: echo "Deploying to prod"
        uses: docker://golang:1.20.3-alpine3.17
        name: Deploy to prod
        shell: sh
        kind: deploy
