apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
metadata:
  stages/v1alpha1:
    - name: Staging
      jobs:
        - Prod
    - name: Production
      jobs:
        - job
jobs:
  Prod:
    uses: ./.cloudbees/workflows/deploy-with-rollout.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
  job:
    needs:
      - Prod
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
