apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true

jobs:
  release:
    uses: ./.cloudbees/workflows/my-workflow-6.yaml
    with:
      manifest: ${{ inputs.manifest }}
  