apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true
jobs:
  deploy-to-dev:
    uses: urvashisingh/my-cbp-app/.cloudbees/workflows/deploy-qa.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: dev
  deploy-to-qa:
    needs: deploy-to-dev
    uses: urvashisingh/my-cbp-app/.cloudbees/workflows/deploy-qa.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: test    
  deploy-to-prod:
    needs: deploy-to-qa
    uses: urvashisingh/my-cbp-app/.cloudbees/workflows/deploy-qa.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: us-prod    