apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  deploy-to-dev:
    uses: ./.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: dev
  deploy-to-qa:
    needs:
      - qa_appr
    uses: ./.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: qa
  deploy-to-prod:
    needs:
      - prod_appr
    uses: ./.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: prod
  publish-evidence:
    steps:
      - name: publish evidence
        with:
          content: This is evidence
        uses: cloudbees-io/publish-evidence-item@v1
      - name: publish second evidence
        with:
          content: This is another evidence
        uses: cloudbees-io/publish-evidence-item@v1
    needs: deploy-to-dev
  qa_appr:
    needs: deploy-to-dev
    with:
      approvers: 0a808e26-f884-11ec-aa0a-42010a83ae55,0cb88e48-03d3-11eb-9d67-42010a83ae35
      disallowLaunchByUser: false
      instructions: pls approve!
      approvalInputs: |
        {}
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  prod_appr:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    needs: deploy-to-qa
    with:
      approvers: 0a808e26-f884-11ec-aa0a-42010a83ae55,0cb88e48-03d3-11eb-9d67-42010a83ae35
      disallowLaunchByUser: false
      instructions: pls approve!
      approvalInputs: |
        {}
