apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true

jobs:
  deploy-to-dev:
    uses: ./.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: dev
  deploy-to-qa:
    needs: deploy-to-dev
    uses: ./.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: qa    
  deploy-to-prod:
    needs: deploy-to-qa
    uses: ./.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: prod    
  publish-evidence:
    steps:
      - name: publish evidence
        with:
          content: This is evidence
        uses: cloudbees-io/publish-evidence-item@v1
      - name: publish second evidence
        with:
          content: This is another evidence
        uses: cloudbees-io/publish-evidence-item@v1
    needs: deploy    
     
