apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true

jobs:
  deploy-to-dev:
    uses: ./deploy.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: us-env
  deploy-to-prod:
    uses: urvashisingh/my-cbp-app/.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: us-env2    
