apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true

jobs:
  print:
    steps:
      - name: Print manifest
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "${{ inputs.manifest }}"
