apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: staged-workflow-sample
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
      patch-release:
        type: boolean
        default: false
        description: Check if this is a patch release
      staging-db:
        type: choice
        options:
          - mysql
          - postgresql
        default: postgresql
        required: true
        description: The database to use for staging environment deployment
metadata:
  stages/v1alpha1:
    - name: preprod-us-west-2
      jobs:
        - deploy-to-preprod-us-west-2
        - approval-job-west
    - name: preprod-us-east-1
      jobs:
        - deploy-to-preprod-us-east-1
        - approval-job-east
jobs:
  deploy-to-preprod-us-west-2:
    steps:
      - name: Deploy to preprod-us-west-2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to preprod-us-west-2"
  approval-job-west:
    with:
      disallowLaunchByUser: false
      instructions: some
      approvalInputs: |
        options-to-choose-from:
          type: choice
          options:
            - op1
            - op2
          default: op2
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    needs:
      - deploy-to-preprod-us-west-2
  deploy-to-preprod-us-east-1:
    needs:
      - approval-job-west
    steps:
      - name: Deploy to preprod-us-east-1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to preprod-us-east-1"
  approval-job-east:
    with:
      disallowLaunchByUser: false
      instructions: some
      approvalInputs: |
        options-to-choose-from:
          type: choice
          options:
            - op1
            - op2
          default: op2
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    needs:
      - deploy-to-preprod-us-east-1
