apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Try JQ

on:
  workflow_dispatch:

jobs:
  jq:
    steps:
      - uses: docker://urvashisingh/jq:0.0.1
        shell: sh
        run: |
          echo '{ "greet": hello world" }' | jq '.greet'
