apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow-params
on:
  workflow_dispatch:
    inputs:
      input1:
        type: string
        default: default-string1
        required: true
      input2:
        type: string
        required: true
      manifest:
        type: string
        default: '{"type":"string","required":true}'
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
